### PR TITLE
LPS-154648 Refactor test WalkthroughPopover#FinalStepCanTransitionToHotSpotMode

### PR DESCRIPTION
**Pull request by susanchen3**
**Background**
When user clicks close button on final step, the process ends. 

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-154648

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:test:sf

**Comment by susanchen3** [comment]
ci:test:frontend

**Comment by susanchen3** [comment]
Test failures are unrelated :heavy_check_mark:  Walkthrough tests are passing now! :tada: 

@diegonvs I think you can manually forward with my test fix :)

**Comment by diegonvs** [comment]
ok @susanchen3, thank you! :peepo-swim:

**Pull request closed without merging**
