### PR TITLE
LPS-171283 Add logging to debug the process

### PR DESCRIPTION
**Pull request by sofiamendozalr**
- Add log messages
- tmp
- LPS-171283 DO NOT MERGE Only run failing test

### CODE REVIEW

**Comment by sofiamendozalr** [comment]
ci:test

**Comment by sofiamendozalr** [comment]
We put some traces to debug the code so, can you please execute this and send us the log? 
Thank you so much!

**Comment by susanchen3** [comment]
ci:test:bundle

**Comment by susanchen3** [comment]
Hey Sofia! Instead of waiting for me to test next time, you can check the liferay log on CI when the test is done running.

**Comment by sofiamendozalr** [comment]
> Hey @sofiamendozalr! Sorry I didn't see the PR until now, I didn't get an email notification for it. Instead of waiting for me to test next time, you can check the Liferay log on CI when the test is done running.
> 
> 1. Click on the **Testray Build** of the [comment](https://github.com/susanchen3/liferay-portal/pull/133#issuecomment-1462602039) above
>    ex. **Testray Build:**[[master] ci:test:default - sofiamendozalr > susanchen3 - PR#133 - 2023-03-09[09:35:15]](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2226404132)
> 2. Click on **Results** tab on the top left
> 3. Click on the **Case** name
>    ex. [LocalFile.Locale#ViewLocaleInNewVirtualInstance](https://testray.liferay.com/home/-/testray/case_results/2226417997?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2226404132%26cur%3D1%26delta%3D200%26tab%3Druns%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
> 4. Click on **Liferay Log**
>    ex. https://testray.liferay.com/reports/production/logs/2023-03/test-1-40/test-portal-acceptance-pullrequest(master)/485/functional-tomcat90-mysql57-jdk8/0/0/liferay-log.txt.gz?authuser=0
> 
> Let me know if the logs helped or if you need me to test anything else.

Hey Susan! I did that, I checked the log on CI and compared it with my local log.
Thank you so much!

**Comment by sofiamendozalr** [comment]
ci:test

**Pull request closed without merging**
