### PR TITLE
LPS-164301 Enable DB Paritioning for all poshi tests

### PR DESCRIPTION
**Pull request by susanchen3**
https://issues.liferay.com/browse/LPS-164301

### CODE REVIEW

**Comment by susanchen3** [comment]
ci:help

**Comment by susanchen3** [comment]
ci:test:acceptance-functional

**Comment by susanchen3** [comment]
ci:test:acceptance-functional

**Comment by susanchen3** [comment]
ci:test:acceptance-functional - retriggering as blocker is fixed upstream

**Comment by susanchen3** [comment]
ci:test:acceptance-functional

**Comment by susanchen3** [comment]
Not seeing any obvious failures, going to trigger more tests

**Comment by susanchen3** [comment]
ci:test:upstream-functional

**Comment by susanchen3** [comment]
ci:stop:acceptance-functional

**Comment by susanchen3** [comment]
results are being blocked by [COMMERCE-10141](https://issues.liferay.com/browse/COMMERCE-10141)

**Comment by vicnate5** [comment]
@susanchen3 That commerce error shouldn't be happening on a majority of test runs. I am just gonna re-run this, I think we have a high chance of getting results we can use now.

If the results look workable, will announce this to the team tomorrow.

**Comment by susanchen3** [comment]
@vicnate5 the results look good to analyze, not seeing the Commerce error

**Pull request closed without merging**
